// code/angular2/3-third-party-integration/src/app/app.component.ts
import { Component } from '@angular/core';
import NVD3Chart from './nvd.chart.component';

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

@Component({
  selector: 'app-root',
  template: `
<div>
  <div style="float: left">
      <svg width="350" height="350"
        (mousedown)="mouseDown($event)"
        (mousemove)="mouseMove($event)"
        (mouseup)="mouseUp($event)"
        >
        <svg:g
          square-box
          *ngFor="let box of boxes"
          [box]="box"
          [selected]="box.id == currentId"
          ></svg:g>
      </svg>
  </div>
  <div style="float: left"><nvd3-chart [positions]="boxes"></nvd3-chart></div>
</div>
  `
})
export class AppComponent {

  currentId = null;
  boxes = [];
  offsetX;
  offsetY;


  ngOnInit() {
    for (let i=0; i < 2000; i++) {
      const id = i;
      const x = getRandomInt(0, 500);
      const y = getRandomInt(0, 500);
      const box = { id, x, y };
      this.boxes.push(box);
    }
  }

  mouseDown(event) {
    const id = Number(event.target.getAttribute("dataId"));
    const box = this.boxes[id];
    const mouseX = event.clientX;
    const mouseY = event.clientY;
    this.offsetX = box.x - mouseX;
    this.offsetY = box.y - mouseY;
    this.currentId = id;
  }

  mouseMove(event) {
    if (this.currentId !== null) {
      this.updateBox(this.currentId, event.clientX + this.offsetX, event.clientY + this.offsetY);
    }
  }

  mouseUp($event) {
    this.currentId = null;
  }

  updateBox(id, x, y) {
    this.boxes[id] = { id, x, y };
  }
}

// code/react/3-third-party-integration/src/App.js
/* @flow */

import React from 'react';
import {List} from 'immutable';

import Box from './Box';
import Chart from './Chart';


export default class App extends React.Component {
    constructor(props) {
        super(props);
        const {boxes} = this.props;
        this.state = {
            boxes: List(boxes),  // eslint-disable-line new-cap
            currentId: null
        };
    }

    render() {
        const {boxes, currentId} = this.state;
        
        let unselectedBoxes = [];
        let selectedBox;
        
        boxes.forEach(box => {
            if (box.id === this.state.currentId) { 
                selectedBox = <Box key={box.id} box={box} selected={true} />;
            } else {
                unselectedBoxes.push(<Box key={box.id} box={box} selected={false} /> );
            }
        });
        
        const style = {
            cursor: selectedBox ? 'pointer' : 'auto'
        };
        
        return (
            <div>
                <svg width="550" height="550" style={style}
                     onMouseDown={(event) => this.onMouseDown(event)}
                     onMouseUp={(event) => this.onMouseUp(event)}
                     onMouseMove={(event) => this.onMouseMove(event)}
                >
                    <g>
                        { unselectedBoxes }
                        { selectedBox }
                    </g>
                </svg>
                <div style={{float: 'left'}}>
                    <Chart positions={boxes} dragInProgress={currentId !== null}/>
                </div>
            </div>);
    }

    onMouseDown(event) {
        const id = Number(event.target.getAttribute("data-id"));
        const {boxes} = this.state;
        const box = boxes.get(id);
        const mouseX = event.clientX;
        const mouseY = event.clientY;
        this.offsetX = box.x - mouseX;
        this.offsetY = box.y - mouseY;
        this.setState({
            currentId: id
        })
    }

    onMouseUp(event) {
        this.setState({
            currentId: null
        })
    }

    onMouseMove(event) {
        if (this.state.currentId !== null) {
            this.updateBox(this.state.currentId, event.clientX + this.offsetX, event.clientY + this.offsetY);
        }
    }

    updateBox(id, x, y) {
        const {boxes} = this.state;
        const modifiedBox = {
            id,
            x,
            y
        };
        const modifiedBoxes = boxes.set(id, modifiedBox);
        this.setState({
            boxes: modifiedBoxes
        });
    }

}
