// code/angular2/3-third-party-integration/src/app/app.component.ts
import { Component } from '@angular/core';
import NVD3Chart from './nvd.chart.component';

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

const numberOfBoxes = 50;

@Component({
  selector: 'app-root',
  template: `
<div>
  <div style="float: left">
      <svg width="350" height="350"
        (mousedown)="mouseDown($event)"
        (mousemove)="mouseMove($event)"
        (mouseup)="mouseUp($event)"
        >
        <svg:g
          square-box
          *ngFor="let box of boxes"
          [box]="box"
          [selected]="box.id == currentId"
          ></svg:g>
      </svg>
  </div>
  <div style="float: left"><nvd3-chart [positions]="boxes"></nvd3-chart></div>
</div>
  `
})
export class AppComponent {

  currentId = null;
  boxes = [];
  offsetX;
  offsetY;


  ngOnInit() {
    for (let i=0; i < numberOfBoxes; i++) {
      const id = i;
      const x = getRandomInt(0, 500);
      const y = getRandomInt(0, 500);
      const box = { id, x, y };
      this.boxes.push(box);
    }
  }

  mouseDown(event) {
    const id = Number(event.target.getAttribute("dataId"));
    const box = this.boxes[id];
    const mouseX = event.clientX;
    const mouseY = event.clientY;
    this.offsetX = box.x - mouseX;
    this.offsetY = box.y - mouseY;
    this.currentId = id;
  }

  mouseMove(event) {
    if (this.currentId !== null) {
      this.updateBox(this.currentId, event.clientX + this.offsetX, event.clientY + this.offsetY);
    }
  }

  mouseUp($event) {
    this.currentId = null;
  }

  updateBox(id, x, y) {
    this.boxes[id] = { id, x, y };
  }
}

// code/react/0-start/src/App.js
/* @flow */

import React from 'react';
import Box from './Box';

function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
}

export default class App extends React.Component {
    constructor(props) {
        super(props);
        const {numberOfBoxes} = this.props;
        const boxes = [];
        for (let i=0; i < numberOfBoxes; i++) {
            const id = i;
            const x = getRandomInt(0, 500);
            const y = getRandomInt(0, 500);
            const box = {
                id,
                x,
                y
            };
            boxes.push(box);
        }
        this.state = {
            boxes,
            currentId: null
        };
    }

    render() {
        const {boxes} = this.state;
        return (
            <div>
                <svg width="550" height="550"
                     onMouseDown={(event) => this.onMouseDown(event)}
                     onMouseUp={(event) => this.onMouseUp(event)}
                     onMouseMove={(event) => this.onMouseMove(event)}
                >
                    <g>
                        {
                            boxes.map((box, index) => <Box key={box.id} box={box}
                                                           selected={box.id === this.state.currentId}/>)
                        }
                    </g>
                </svg>
            </div>);
    }

    onMouseDown(event) {
        const id = Number(event.target.getAttribute("data-id"));
        const {boxes} = this.state;
        const box = boxes[id];
        const mouseX = event.clientX;
        const mouseY = event.clientY;
        this.offsetX = box.x - mouseX;
        this.offsetY = box.y - mouseY;
        this.setState({
            currentId: id
        })
    }

    onMouseUp(event) {
        this.setState({
            currentId: null
        })
    }

    onMouseMove(event) {
        if (this.state.currentId !== null) {
            this.updateBox(this.state.currentId, event.clientX + this.offsetX, event.clientY + this.offsetY);
        }
    }

    updateBox(id, x, y) {
        const {boxes} = this.state;
        const box = boxes[id];
        box.x = x;
        box.y = y;
        this.setState({boxes});
    }

}
